### PR TITLE
:wrench: build: Updated to use Version Catalog

### PR DESCRIPTION
**Pull request by OdisBy**
## Task

This pull request refers to task LOR-XX

- [x] Does not apply to this pull request

## Description

Updated the project to start to use Version Catalog, the purpose of this change is to implement multi modules in the app

## Types of changes #

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected).

## What changed: #

- [ ] UI
- [ ] Business rule
- [ ] Documentation
- [x] Gradle or Build
- [ ] Navigation
- [ ] Tests
- [ ] Resource files
- [ ] Project architecture
- [ ] Code style

## Checklist #

- [x] Have tested the changes.
- [ ] Met all the acceptance requirements of this task.
- [x] Verified if branch is up-to-date with `development` (if not - rebase it or merge it).
- [ ] Resolve git conflicts

## If any of the acceptance criteria are not met, please explain why below #
What is the criteria? Why it is different?

### CODE REVIEW

**Review by hartmannjean — APPROVED** [review]
👌🏼

**Review by softdevandre — CHANGES_REQUESTED** [review]
```
Failed to resolve: androidx.test.ext:androidx-test-ext-junit:1.1.5
Failed to resolve: androidx.compose:androidx-compose-compose-bom:2023.09.02
```

**Review by hartmannjean — APPROVED** [review]
👌🏼

**Review by softdevandre — APPROVED** [review]

**Comment by softdevandre** [comment]
✅

**Pull request merged**
